version: '2'
services:
  solrsysapi-app:
    image: pablobalegno/solrsysapi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://solrsysapi-mysql:3306/solrsysapi?useUnicode=true&characterEncoding=utf8&useSSL=false'
      - APP_SLEEP=10
    ports:
      - "80:8888"
  solrsysapi-mysql:
    image: 'mysql:5.7.26'
    volumes:
      - "${WEBAPP_STORAGE_HOME}/volumes/SolrSysApi/mysql/:/var/lib/mysql/"
    environment:
      - MYSQL_ROOT_PASSWORD=meli2019
      - MYSQL_DATABASE=solrsysapi
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp