version: '2'
services:
  solrsysapi-mysql:
    image: mysql:5.7.26
    volumes:
        - ~/volumes/SolrSysApi/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=meli2019
      - MYSQL_DATABASE=solrsysapi
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
